export {
  category,
  condition,
  platform,
  publisher,
  genre,
  accessories,
  officialCheck,
  cardGames,
  cardSale,
  cardPublisher,
  AFMakers,
  figurineMaker,
};

let category = [
  "Console",
  "Games",
  "Accessories",
  "Action Figures",
  "Trading Card Game",
  "Board Game",
  "Figurines",
  "N/A",
];
let condition = ["New", "Used", "Complete", "Loose", "Broken", "N/A"];
// THIS IS FOR GAMES AND CONSOLES
let platform = [
  "NES",
  "SNES",
  "N64",
  "GameCube",
  "Wii",
  "Wii U",
  "Switch",
  "GameBoy/Color",
  "GameBoy Advance",
  "Nintendo DS",
  "Nintendo 3DS",
  "PS1",
  "PS2",
  "PS3",
  "PS4",
  "PS5",
  "PSP",
  "PSVita",
  "Xbox",
  "Xbox 360",
  "Xbox One",
  "Xbox Series",
  "Genesis",
  "Game Gear",
  "Sega CD",
  "32X",
  "Sega Saturn",
  "DreamCast",
  "N/A",
];
let publisher = [
  "Nintendo",
  "Microsoft",
  "Sony",
  "Bandai Namco",
  "Ubisoft",
  "EA Games",
  "Square Enix",
  "Konami",
  "Sega",
  "Capcom",
  "Rare",
  "N/A",
];
let genre = [
  "Platform",
  "FPS",
  "Survival Horror",
  "Metroidvania",
  "Visual Novels",
  "Action RPG",
  "RougeLikes",
  "JRPG",
  "Simulation",
  "Fighting",
  "Party",
  "Turn-Based Strategy",
  "Real-Time Strategy",
  "Racing",
  "Sports",
  "Open World",
  "Horror",
  "N/A",
];
// THESE ARE FOR ACCESSORIES
let accessories = [
  "Game Controller",
  "Memory Cards",
  "Audio/Video Cable",
  "Console Cases",
  "CD Cases",
  "Cartridge Cases",
  "Add-Ons/Peripherals",
  "N/A",
];
let officialCheck = ["First Party", "Third Party", "Custom"];
// THESE ARE FOR TRADING CARD GAMES
let cardGames = [
  "Magic: The Gathering",
  "Pokemon Trading Card Game",
  "Yu-Gi-Oh! Trading Card Game",
  "Dungeons and Dragons Icons of the Realms",
  "Cardfight!! Vanguard",
  "Dragon Ball Super",
  "Final Fantasy Trading Card Game",
  "Weiss Schwarz",
  "Transformers TCG",
  "Star Wars Destiny",
  "Ashes: Rise of the Phoenixborn",
  "Game of Thrones: The Card Game",
  "N/A",
];
let cardSale = [
  "Single Card",
  "Single Booster Pack",
  "Boxed Booster Pack",
  "Boxed Set",
  "Custom Collection",
  "N/A",
];
let cardPublisher = [
  "Wizards of the Coast",
  "Pokemong USA",
  "Konami",
  "Score Entertainment",
  "Mattel",
  "Bushiroad",
  "Bandai Namco",
  "Square Enix",
  "Hasbro",
  "Fantasy Flight Games",
  "Plaid Hat Games",
  "N/A",
];
// THESE ARE COMMON ACTION FIGURE MAKERS
let AFMakers = [
  "Hasbro",
  "Mattel",
  "Bandai Spirits",
  "McFarlane Toys",
  "NECA",
  "Hot Toys",
  "DC Multiverse",
  "Diamond Select Toys",
  "Hot Toys",
  "Play Arts Kai",
  "POP!",
  "N/A",
];
// THESE ARE COMMON FIGURINE MAKERS MOSTLY ARE GEARED TOWARD ANIME
let figurineMaker = [
  "Good Smile Company",
  "Megahouse",
  "Kotobukiya",
  "Max Factory",
  "Alter",
  "BanPresto",
  "Orange Rouge",
  "Stronger",
  "Aniplex",
  "Bandai Namco Arts",
  "N/A",
];
